### ISSUE TITLE
Multiple User Chat (Not Retrieving Correctly)

### ISSUE THREAD

**Issue by VenkatachalamVE** [dongido001/flask_chatbot#5] opened 2018-11-21 12:00 UTC
Respected Sir/Madam,
  
                 In Dialogflow, While multiple user chatting at same time, there is some errors occurred while retrieving data, If First User enters value it retrieves correctly but the second user enters the value in the follow-up intent directly, that also gives response instead of fallback intent reponse.

Multiple User can access the chat or not (Accurate Response)?
Kindly Reply Immediately.
Thanking You
Your's Respectfully
Venkatachlam. VE

**Comment by dongido001** [comment] 2018-11-21 13:14
Hi @VenkatachalamVE,

Multiple users can chat at the same time. It's implemented in a way that multiple users chatting with the bot can see the response in [realtime](https://pusher.com/channels) of others (That is if the users are using the same application).

If you don't want to see other users chat, you can remove/comment out the realtime part.

**Comment by VenkatachalamVE** [comment] 2018-11-21 14:02
Thank you for your response. 
Please find the below multiple user chat on same time. This is the problem how to solve it?
sample chat checked

![dongido](https://user-images.githubusercontent.com/42691189/48845954-d8698600-edc3-11e8-84ee-50e414a08e4d.jpg)
![dongido1](https://user-images.githubusercontent.com/42691189/48845955-d8698600-edc3-11e8-819f-06fcf5d8ed82.jpg)

**Comment by dongido001** [comment] 2018-11-21 15:16
Oh I see.

For my above response, I thought it was this project that you were referring to.

Since the problem is from Dialogflow, I will suggest you open the issue directly on the [dialogflow-python-client repo](https://github.com/dialogflow/dialogflow-python-client) so you can get help quickly.

Thanks.

**Comment by dongido001** [comment] 2018-11-23 12:33
I'm closing this since it's not a problem with the app.

**Closed as completed by dongido001** 2018-11-23 12:33 UTC

**Comment by VenkatachalamVE** [comment] 2018-11-26 14:04
Is this problem based on session id?

**Comment by VenkatachalamVE** [comment] 2018-11-26 14:05
def detect_intent_texts(project_id, session_id, text, language_code):
    session_client = dialogflow.SessionsClient()
    session = session_client.session_path(project_id, session_id)
    
    if text:
        text_input = dialogflow.types.TextInput(
            text=text, language_code=language_code)
        query_input = dialogflow.types.QueryInput(text=text_input)
        response = session_client.detect_intent(
            session=session, query_input=query_input)
        
        return response.query_result.fulfillment_text

**Comment by VenkatachalamVE** [comment] 2018-11-26 14:06
Where Can i get session id?

**Comment by dongido001** [comment] 2018-11-26 14:58
Not sure if that might be the problem but it's worth checking.

for the app, I'm using [a constant string- "unique"](https://github.com/dongido001/flask_chatbot/blob/master/index.py#L69) for the session_id for all users. The session_id is meant to be a unique key that differentiates each user that is chatting. 

Maybe try generating a unique key instead and see if it changes anything. If you have your code somewhere, I'd be glad to take a look.
